-- Run this once in Supabase: SQL Editor > New query.
create table if not exists public.issues (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 90),
  category text not null,
  priority text not null check (priority in ('Normal', 'High', 'Urgent')),
  location text not null check (char_length(location) between 2 and 60),
  details text not null check (char_length(details) between 3 and 500),
  reporter text,
  status text not null default 'Open' check (status in ('Open', 'In progress', 'Resolved')),
  reported_at timestamptz not null default now()
);

alter table public.issues enable row level security;

-- A report must identify the reporting flat. This also upgrades an existing
-- SocietyCare table safely; historical blank values are retained as Unknown.
update public.issues set reporter = 'Unknown flat' where reporter is null or trim(reporter) = '';
alter table public.issues alter column reporter set not null;
alter table public.issues drop constraint if exists issues_reporter_not_blank;
alter table public.issues add constraint issues_reporter_not_blank
  check (char_length(trim(reporter)) between 3 and 20);

-- Anyone can submit and view reports. Restrict status changes/deletion to an
-- authenticated committee account after you enable authentication in the app.
create policy "Anyone can view society issues" on public.issues for select using (true);
create policy "Anyone can report an issue" on public.issues for insert with check (true);

-- Realtime makes reports submitted by other residents appear automatically.
alter publication supabase_realtime add table public.issues;
